language: rust
sudo: required
env:
  global:
    - CRATE_NAME=rair
matrix:
  include:
    - os: linux
      env: COV=true
    - os: linux
      rust: nightly
    - os: osx
    - os: windows
    - os: android

    - os: linux
      arch: x86
    - os: windows
      arch: x86
    - os: android
      arch: arm64    

install:
- ci/install.sh
script:
- ci/test.sh
notifications:
  email:
    on_success: never
before_deploy:
- sh ci/deploy.sh
cache: cargo
deploy:
  provider: releases
  api_key:
    secure: QK86c6DSEZDwr8BqJx6a9KLIpLVyMifHPm5VyXtUtex4QkZGL2TcbQqIk0+vpOeSMJqQuGO7T9ASCtGGIWo1jwOOBRDxclRg3H/G5fUFwdOpsUkGt9aaIwjR4o9Afrw375mAAvcz3+DeLRRXXVCSyyClj+EEAO6uxJwf7+SnZxYRDj5ecYBtf2tvHjORwM5AbsWOGgKkAFpvjkWz3mBK0Wv+BUrcran/g44PZ5VljkQ8KS8oLsM7Sl+NPJvqTWbylu+zkDMbo8WZpWVXMO6JbU36rxGB0OarWEV2MsXrU1eACkcao57K6IP98Y9cFGNN0ggUntRE48TY5E2HvXzqSyo0c96xNLm5gMWQ3PjG6JaVDjIBn1e4I2j7v3c3BZA6tl33cGokVoYQ+DNR1J2ABn7hPGmneWVSMzCDmvURVtnwQYyj2QulADFDhSGWoXKjqdLj4yUNrwZeatyJ6Kxcg4PbIH5G/82ofa5oflJs5F3lEm1lw7cgem2Lx/2rrift4zctIhF6+3N8YvODEbKC8XXjjM/GbqM05+3dTKxGciEbhwodvizF6BWEl8pgxW87SaSBO7ZEPqQQHpQhgg6QzBUVGoOb2xNqVPFQM369zDhOK09G5tdXIpfQLI/pgQdAO/ZZTbJD9dL/Y98fO8yPJPT2UvtLGiMC7UqHBXTYkNY=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
